f1=int(input("enter the value of 1 student:"))
f2=int(input("enter the value of 2 student:"))
f3=int(input("enter the value of 3 student:"))
f4=int(input("enter the value of 4 student:"))
f5=int(input("enter the value of 5 student:"))
f6=int(input("enter the value of 6 student:"))
f7=int(input("enter the value of 7 student:"))
my_fruit_list=[f1,f2,f3,f4,f5,f6,f7]
my_fruit_list.sort()
print(my_fruit_list)